#!/bin/sh

set -e

ini=$(cat << EOS
xdebug.remote_enable=${XDEBUG_REMOTE_ENABLE}
xdebug.remote_host=${XDEBUG_REMOTE_HOST:-$(ip route | awk 'NR==1 {print $3}')}
xdebug.remote_port=${XDEBUG_REMOTE_PORT}
xdebug.remote_autostart=${XDEBUG_REMOTE_AUTOSTART}
xdebug.remote_cookie_expire_time=${XDEBUG_REMOTE_COOKIE_EXPIRE_TIME}
xdebug.remote_mode=${XDEBUG_REMOTE_MODE}
xdebug.remote_connect_back=${XDEBUG_REMOTE_CONNECT_BACK}
xdebug.idekey=${XDEBUG_IDEKEY}
EOS
)
echo "${ini}" | grep -E "=.+" >> /usr/local/etc/php/conf.d/my.ini


if [ -n "${HOST_UID}" ]; then
    usermod -u "${HOST_UID}" www-data
fi

if [ -n "${HOST_GID}" ]; then
    groupmod -g "${HOST_GID}" www-data
fi

if [ -e "composer.json" ]; then
    sudo -u www-data composer install
fi

if [ "${1#-}" != "$1" ]; then
	set -- docker-php-entrypoint "$@"
fi

exec "$@"
